### ISSUE TITLE
Determine Minimal CMake Version

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMakePackagingProject#15]
For documentation purposes we should determine what the minimum version of CMake is that we support.

At the moment I know I am using:
-  `include_guard`, which is a 3.10 feature 
   - Could easily be removed though to allow more backwards compatibility
- Directory property `BUILDSYSTEM_TARGETS`, which is added in 3.7
   - I really don't want to do without this

This is just off the top of my head, so more investigation is needed to determine if I'm using other features from 3.7 onwards, or if 3.7 is the rock-bottom version we can support

**Comment by AutonomicPerfectionist** [comment]
Building CMakePackagingProject on CMake version 3.10.2 on Ubuntu 18.04 succeeds, however building a test project with CPP fails.

Stacktrace:

> CMake Error at /usr/share/cmake/cpp/object/ctor.cmake:37 (set_target_properties):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "_cpp__cpp_member_list" is not allowed.
>Call Stack (most recent call first):
>  /usr/share/cmake/cpp/kwargs/ctor.cmake:29 (_cpp_Object_ctor)
>  /usr/share/cmake/cpp/user_api/cpp_find_or_build_dependency.cmake:61 (_cpp_Kwargs_ctor)
>  CMakeLists.txt:5 (cpp_find_or_build_dependency)


>CMake Error at /usr/share/cmake/cpp/target/target_has_property.cmake:53 (get_target_property):
  INTERFACE_LIBRARY targets may only have whitelisted properties.  The
  property "_cpp__cpp_member_list" is not allowed.
>Call Stack (most recent call first):
>  /usr/share/cmake/cpp/object/is_object.cmake:37 (_cpp_target_has_property)
>  /usr/share/cmake/cpp/object/is_not_object.cmake:27 (_cpp_is_object)
>  /usr/share/cmake/cpp/object/get_members.cmake:34 (_cpp_is_not_object)
>  /usr/share/cmake/cpp/object/add_members.cmake:30 (_cpp_Object_get_members)
>  /usr/share/cmake/cpp/object/ctor.cmake:40 (_cpp_Object_add_members)
>  /usr/share/cmake/cpp/kwargs/ctor.cmake:29 (_cpp_Object_ctor)
>  /usr/share/cmake/cpp/user_api/cpp_find_or_build_dependency.cmake:61 (_cpp_Kwargs_ctor)
>  CMakeLists.txt:5 (cpp_find_or_build_dependency)


>CMake Error at /usr/share/cmake/cpp/cpp_print.cmake:25 (message):
>  _cpp_XdD1j is not a handle to an object
>Call Stack (most recent call first):
>  /usr/share/cmake/cpp/object/get_members.cmake:36 (_cpp_error)
>  /usr/share/cmake/cpp/object/add_members.cmake:30 (_cpp_Object_get_members)
>  /usr/share/cmake/cpp/object/ctor.cmake:40 (_cpp_Object_add_members)
>  /usr/share/cmake/cpp/kwargs/ctor.cmake:29 (_cpp_Object_ctor)
>  /usr/share/cmake/cpp/user_api/cpp_find_or_build_dependency.cmake:61 (_cpp_Kwargs_ctor)
>  CMakeLists.txt:5 (cpp_find_or_build_dependency)


>-- Configuring incomplete, errors occurred!

Building with cmake 3.15.3 via snap does not produce errors. This is a restriction in cmake itself where only certain properties can be applied to interface libraries (looking at cmake source, it looks like they must begin with "IMPORTED_" or "INTERFACE_", and there's a predetermined list of whitelisted properties, meaning it would be very difficult to work around this without editing cmake source). This has existed since version 3.9 at least, but was removed sometime after 3.10. Further testing required to find exact version where this is removed.

**Comment by ryanmrichard** [comment]
@AutonomicPerfectionist I wouldn't worry too much about the issues on this repo at the moment. The goal is to overhaul the backend of this repo which will invalidate many of them.

That said, the whitelisting/blacklisting of target properties is an uber annoying "feature" of CMake  (it is also a pain when you are trying to automatically skim targets as you need to know whether a target is an interface/imported when you skim it and I do not know of a great way to determine that). Another option for implementing how the `Object` base class works is to use global properties to store the state (see [this function]( https://github.com/CMakePP/CMakeTest/blob/master/cmake_test/detail_/test_section/private.cmake#L51)). It works basically the same way `global_variable_name = this_ptr + member_name` (`this_ptr` being a random string generated as part of the object's construction). My guess is this will be more backwards compatible.
